name: GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *"  # Atualiza a cada 12h
  workflow_dispatch:        # Permite rodar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          # Perfil
          user: SavioCartaxo
          template: classic
          base: header, activity, community, repositories, metadata

          # Plugins principais
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, scss, dockerfile
          plugin_languages_details: percentage
          plugin_languages_limit: 8

          plugin_activity: yes
          plugin_activity_limit: 10

          plugin_followup: yes

          plugin_stargazers: yes

          plugin_repositories: yes
          plugin_repositories_sort: stars
          plugin_repositories_limit: 6

          plugin_traffic: yes

          # Arquivo gerado
          output_path: github-metrics.svg
